# Generated by Django 4.2.16 on 2024-11-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='preferences',
            new_name='preference',
        ),
    ]
