# Generated by Django 4.2.16 on 2024-12-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='default@example.com', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='23igjo23tuowet', max_length=100, unique=True),
        ),
    ]
