# Generated by Django 4.2.16 on 2024-12-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_email_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
