# Generated by Django 4.2.16 on 2024-12-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default="Biography: Hi! I'm new to Comm-you-nity, plz hmu if yall are interested in going out together! insta: @", max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='New User', max_length=100),
        ),
    ]
